# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

[era.taika]
kanji = "大化"
english = "Taika"
start = 0645-07-20
end = 0650-03-25

[era.hakuchi]
kanji = "白雉"
english = "Hakuchi"
start = 0650-03-25
end = 0654-11-27

[era.shucho]
kanji = "朱鳥"
english = "Shuchō"
start = 0686-08-17
end = 0686-10-04

[era.taiho]
kanji = "大宝"
english = "Taihō"
start = 0701-05-07
end = 0704-06-20

[era.keiun]
kanji = "慶雲"
english = "Keiun"
start = 0704-06-20
end = 0708-02-11

[era.wado]
kanji = "和銅"
english = "Wadō"
start = 0708-02-11
end = 0715-10-07
