# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

[era.gentoku]
kanji = "元徳"
english = "Gentoku"
start = 1329-09-30
end = 1332-05-31

[era.shokyo]
kanji = "正慶"
english = "Shōkyō"
start = 1332-05-31
end = 1333-07-15

[era.kenmu]
kanji = "建武"
english = "Kenmu"
start = 1334-03-13
end = 1338-10-19

[era.ryakuo]
kanji = "暦応"
english = "Ryakuō"
start = 1338-10-19
end = 1342-06-09

[era.koei]
kanji = "康永"
english = "Kōei"
start = 1342-06-09
end = 1345-11-23

[era.jowa]
kanji = "貞和"
english = "Jōwa"
start = 1345-11-23
end = 1350-04-12

[era.kanno]
kanji = "観応"
english = "Kannō"
start = 1350-04-12
end = 1352-11-12

[era.bunna]
kanji = "文和"
english = "Bunna"
start = 1352-11-12
end = 1356-05-07

[era.enbun]
kanji = "延文"
english = "Enbun"
start = 1356-05-07
end = 1361-05-12

[era.koan]
kanji = "康安"
english = "Kōan"
start = 1361-05-12
end = 1362-10-19

[era.joji]
kanji = "貞治"
english = "Jōji"
start = 1362-10-19
end = 1368-03-15

[era.oan]
kanji = "応安"
english = "Ōan"
start = 1368-03-15
end = 1375-04-06

[era.eiwa]
kanji = "永和"
english = "Eiwa"
start = 1375-04-06
end = 1379-04-17

[era.koryaku]
kanji = "康暦"
english = "Kōryaku"
start = 1379-04-17
end = 1381-03-28

[era.eitoku]
kanji = "永徳"
english = "Eitoku"
start = 1381-03-28
end = 1384-03-27

[era.shitoku]
kanji = "至徳"
english = "Shitoku"
start = 1384-03-27
end = 1387-10-13

[era.kakei]
kanji = "嘉慶"
english = "Kakei"
start = 1387-10-13
end = 1389-03-15

[era.koo]
kanji = "康応"
english = "Kōō"
start = 1389-03-15
end = 1390-04-20

[era.meitoku]
kanji = "明徳"
english = "Meitoku"
start = 1390-04-20
end = 1394-08-10
