# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

[tool.ruff]
line-length = 79

[tool.ruff.lint]
ignore = ["D100", "D103", "D203", "D212", "COM812", "FA102", "ISC001"]
select = ["ALL"]
