# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

[tool.ruff]
line-length = 79

[tool.ruff.lint]
ignore = [
  "D100",
  "D103",
  "D203",
  "D212",
  "ANN001",
  "ANN201",
  "COM812",
  "ISC001",
]
select = ["ALL"]
