// SPDX-FileCopyrightText: None
//
// SPDX-License-Identifier: CC0-1.0

= Dataset of the Japanese era
:github-url: https://github.com
:project-url: {github-url}/sorairolake/japanese-era-dataset
:shields-url: https://img.shields.io
:ci-badge: {shields-url}/github/actions/workflow/status/sorairolake/japanese-era-dataset/CI.yaml?branch=develop&style=for-the-badge&logo=github&label=CI
:ci-url: {project-url}/actions?query=branch%3Adevelop+workflow%3ACI++
:enwp-url: https://en.wikipedia.org
:enwp-article-url: {enwp-url}/wiki/Japanese_era_name
:assets-dir: assets
:yaml-dir: {assets-dir}/yaml
:pyyaml-url: {github-url}/yaml/pyyaml
:tomli-w-url: {github-url}/hukkin/tomli-w
:jawp-url: https://ja.wikipedia.org
:jawp-article-url: {jawp-url}/wiki/%E5%85%83%E5%8F%B7%E4%B8%80%E8%A6%A7_(%E6%97%A5%E6%9C%AC)
:reuse-spec-url: https://reuse.software/spec/

image:{ci-badge}[CI,link={ci-url}]

link:README.ja.adoc[日本語]

This repository contains a dataset of the {enwp-article-url}[Japanese era] in
YAML format.

== Structure

The era is represented by the associative array.

.For example, the associative array representing the Heisei era is:
[source,yaml]
----
era:
  heisei:
    number: 231
    kanji: 平成
    kyujitai: null
    english: Heisei
    start: 1989-01-08
    end: 2019-05-01
----

.The meanings of the key/value pairs are as follows:
`number`::

  The position of the era in the list of Japanese era names. `null` if not in
  the list.

`kanji`::

  The era name in kanji.

`kyujitai`::

  The era name in kyūjitai. `null` if same as `kanji`.

`english`::

  The era name in English.

`start`::

  The start date of the era.

`end`::

  The end date of the era. `null` for the current era.

.The following keys exist in the Nanboku-chō period:
`southern-number`::

  The position of the era in the list of the Southern Court era names. This may
  be `null`.

`northern-number`::

  The position of the era in the list of the Northern Court era names. This may
  be `null`.

=== Directory structure

.The YAML files representing the eras are as follows:
link:{yaml-dir}/asuka.yaml[]::

  It contains the eras in the Asuka period (from _Taika_ to _Wadō_).

link:{yaml-dir}/nara.yaml[]::

  It contains the eras in the Nara period (from _Reiki_ to _Enryaku_).

link:{yaml-dir}/heian.yaml[]::

  It contains the eras in the Heian period (from _Daidō_ to _Genryaku_).

link:{yaml-dir}/kamakura.yaml[]::

  It contains the eras in the Kamakura period (from _Bunji_ to _Karyaku_).

link:{yaml-dir}/southern-court.yaml[]::

  It contains the eras of the Southern Court (from _Gentoku_ to _Genchū_).

link:{yaml-dir}/northern-court.yaml[]::

  It contains the eras of the Northern Court (from _Gentoku_ to _Meitoku_).

link:{yaml-dir}/muromachi.yaml[]::

  It contains the eras in the Muromachi period (from _Ōei_ to _Genki_).

link:{yaml-dir}/azuchi-momoyama.yaml[]::

  It contains the eras in the Azuchi–Momoyama period (from _Tenshō_ to
  _Keichō_).

link:{yaml-dir}/edo.yaml[]::

  It contains the eras in the Edo period (from _Genna_ to _Keiō_).

link:{yaml-dir}/modern.yaml[]::

  It contains the eras of the modern era (after _Meiji_).

=== Convert to other formats

This project contains Python scripts for converting YAML files to JSON files or
TOML files.

IMPORTANT: {pyyaml-url}[_PyYAML_] is required for conversion.

.To convert to JSON files
[source,sh]
----
./scripts/yaml2json.py
----

This will output JSON files in the `{assets-dir}/json` directory.

.To convert to TOML files
[source,sh]
----
./scripts/yaml2toml.py
----

This will output TOML files in the `{assets-dir}/toml` directory.

IMPORTANT: {tomli-w-url}[_Tomli-W_] is required for conversion.

NOTE: Keys with `null` values ​​are removed.

== Acknowledgment

.This dataset was created using the following:
* {jawp-article-url}[元号一覧 (日本)] on the Japanese Wikipedia (for the era
  name in kanji).
* {enwp-article-url}[Japanese era name] on the English Wikipedia (for the era
  name in English).
* {github-url}/nagataaaas/Japanera (for the start date and the end date).

== License

Unless otherwise noted, the contents of this repository are distributed under
the terms of the _CC0 1.0 Universal_.

This project is compliant with version 3.0 of the
{reuse-spec-url}[_REUSE Specification_]. See copyright notices of individual
files for more details on copyright and licensing information.
