# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "master"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          npm ci
          npx prettier -v
          pip install yamllint
          yamllint -v
      - name: Check code formatted
        run: npx prettier -c assets/yaml/*.yaml
      - name: Check no lint warnings
        run: yamllint -s assets/yaml/*.yaml

  deno-test:
    name: Test Deno scripts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.x
      - name: Check code formatted
        run: deno fmt --check scripts/*.ts
      - name: Check no lint warnings
        run: deno lint scripts/*.ts
      - name: Type-check
        run: deno check scripts/*.ts
