# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "master"

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          npm ci
          npx prettier -v
          pip install yamllint
          yamllint -v
      - name: Run formatter in check mode
        run: npx prettier -c "**.{json,md,yaml,yml}"
      - name: Run linter
        run: yamllint -s assets/yaml/*.yaml

  deno-test:
    name: Test Deno scripts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.x
      - name: Run formatter in check mode
        run: deno fmt --check deno.jsonc scripts/*.ts
      - name: Run linter
        run: deno lint scripts/*.ts
      - name: Type-check
        run: deno check scripts/*.ts
