# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup uv
        uses: astral-sh/setup-uv@v7.5.0
        with:
          python-version: "3.14" # latest stable version of Python 3
      - name: Install dependencies
        run: |
          npm ci
          npx prettier -v
      - name: Run formatter in check mode
        run: npx prettier -c "**.{json,md,yaml,yml}"
      - name: Run linter
        run: uvx yamllint -s assets/yaml/*.yaml

  deno-test:
    name: Test Deno scripts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.4
        with:
          deno-version: v2.x
      - name: Run formatter in check mode
        run: deno fmt --check deno.jsonc scripts/*.ts
      - name: Run linter
        run: deno lint scripts/*.ts
      - name: Type-check
        run: deno check scripts/*.ts
